FROM node:12.14.0-alpine

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json ./

RUN yarn install

COPY --chown=node:node ./src/ ./src/

RUN yarn build

ENV ADDRESS=0.0.0.0
ENV PORT=5000

EXPOSE 5000
CMD [ "node", "./dist/index.js" ]
