FROM node:12.22.0-alpine

RUN apk add --no-cache python gcc g++ make

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json ./

RUN yarn install

COPY --chown=node:node ./src/ ./src/

RUN cat ./src/tsconfig.json

ENV NODE_ENV=production
RUN yarn build

ENV ADDRESS=0.0.0.0
ENV PORT=4000
EXPOSE 4000


CMD [ "node", "./dist/index.js" ]
